### ISSUE TITLE
API rename the $sync_member_fields to be more verbose 

### ISSUE THREAD

**Issue by camfindlay** [camfindlay/silverstripe-apes#10]
When setting which fields to sync to mailchimp in the config yaml you use the following:

``` yml
Member:
  sync_member_fields:
    FirstName: FNAME
    Surname: LNAME
    Email: EMAIL
    Country: COUNTRY
```

If you didn't know that the APES module was installed there is nothing here that indicates what is being sync'd.

Suggest we refactor this static name to $sync_fields_to_mailchimp which is more useful.
